### ISSUE TITLE
Hello, there are a lot of null values in IC calculated by using ArcGIS10_1_Toolbox tool. How can I solve this problem? Data source: airborne radar

### ISSUE THREAD

**Issue by xxlddgs** [HydrogeomorphologyTools/Connectivity-Index-ArcGIS-toolbox#4]
Hello, there are a lot of null values in IC calculated by using ArcGIS10_1_Toolbox tool. How can I solve this problem? Data source: airborne radar

**Comment by HydrogeomorphologyTools** [comment]
Hello, thanks for reaching us.
Could you please elaborate more on that? Is the DTM correctly pit-filled before usage? Is there any sink or no data remaining?
Is it a very flat area that might induce overflow in the downslope weighted component?

Did you try also SedInConnect as a procedural benchmark? You can find the stand-alone installer at the releases link.

**Comment by xxlddgs** [comment]
Hello, thank you for your reply.

Our research area belongs to the hilly and gully region, with an elevation of 750-956m.

Method 1: Firstly, Taudem software was used to fill the pit for DTM (0.1m), then ArcGIS10_1_Toolbox tool was used to calculate the roughness, and finally, Connectivity Index model was used to calculate the result, as shown in FIG.1. It can be seen that almost half of the regions have serious data missing. I checked the source data, but the source data is correct. I tried to find the problem, which seems to be missing data in the process of dividing in the model. I would like to ask the author how to solve such problems.
![1](https://user-images.githubusercontent.com/91003433/190362580-b50710b1-64ac-4512-b2e4-19553e273052.png)

Method 2: At the same time, I used SedInConnect as the program benchmark as Figure 2, but there were some problems in the color representation of the figure produced by SedInConnect, and the output color could not be selected, which was difficult to distinguish.
![2](https://user-images.githubusercontent.com/91003433/190362504-fa1f8f7c-1c69-4dba-b4ed-c61b89f80b19.png)

Therefore, I prefer method one. Please help me solve this problem. I will be very grateful.

**Comment by HydrogeomorphologyTools** [comment]
The maps you're presenting are actually very similar.
The SedInConnect outcome can be loaded in any GIS, the ArcGIS coloring scheme would have applied the same way to the SedInConnect outcome since the SedInConnect splash image is just a raw preview.

To me, it looks like the input files (probably the DTM if you did not use the roughness option in SedInConnect but you let the tool compute it) have some issues. NoData presence (or NoData code number) in the DTM tends to generate exactly the patterns you show. The same patterns come to light in the presence of local sinks that are not correctly removed (pit fill or other methods).

Sometimes those patterns are also generated by the TauDEM option "check for edge contamination" available for some of the flow algorithms.

I suggest you import the SedInConnect result and input files and back-analyze where the issue has originally started and then propagated into the results. Those violet-white spots on the IC map are most likely focusing on a no-data pixel (or more than one). After roughness computation did you prepare correctly the W factor for SedInConnect? (invert values e set the lower threshold to avoid division by zero). it could be like you said considering the very high resolution, you can have a try first at 0.5m or 1m and then increase the resolution to monitor where the effect becomes significant. Those patterns though look very much like NoData spots that might be in the input data or result from the analysis (e.g. slope 0 or W zero of Rough 1).

I don't know exactly the scale of your application but I'd like to share some insights with you on a recent poster we presented at IAG-ICG 2022 in Coimbra.





![IAG_Coimbra_Roughness_IC](https://user-images.githubusercontent.com/13150311/190617243-e1c2df40-502e-430e-995f-7bd564494894.png)
